# Done to increase the memory available to Gradle.
org.gradle.jvmargs = -Xmx4G
org.gradle.parallel = true

# Mod Properties
mod_id = config_n_utils
mod_name = Millie's Config & Utils
mod_version = 1.0.0
mod_description = Small config and utils library for creating and managing .properties, .json, .json5 and .yaml/yml configs and saving on duplicate util classes between my projects
mod_license = MIT
mod_authors = JustMili

maven_group = net.justmili.libs
archives_base_name = ConfigAndUtilsLib

minecraft_version_constraint = 1.21.11

# Dependencies
mod_menu = 17.0.0