# Done to increase the memory available to Gradle.
org.gradle.jvmargs = -Xmx4G
org.gradle.parallel = true

# Mod Properties
mod_id = milliesconfiglib
mod_name = Millie's Config Lib
mod_version = 1.0.0
mod_description = Small config library for creating and managing .properties and .json config files
mod_license = MIT
mod_authors = JustMili

maven_group = net.justmili.config
archives_base_name = MilliesConfigLib

minecraft_version_constraint = 1.21.11

# Dependencies
mod_menu = 17.0.0