# Done to increase the memory available to Gradle.
org.gradle.jvmargs = -Xmx4G
org.gradle.parallel = true

# Mod Properties
mod_id = milliescorelibs
mod_name = Millie's Core Libraries
mod_version = 1.0.0
mod_description = An open-source multiloader config, util and cross-loader API library
mod_license = MIT
mod_authors = JustMili

maven_group = net.justmili.libs
archives_base_name = MilliesCoreLibs
enabled_platforms = fabric,forge

minecraft_version_constraint_forge = [1.20.1]
minecraft_version_constraint_fabric = 1.20.1
supported_versions = 1.20.1

# Dependencies
mod_menu = 7.2.2